# Question - 1 Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [44]:
def Alex_Theo_Vander(input_arr,powers):
    a = input_arr
    n = powers
    Arr = np.array([a[i]**j for i in range(len(a)) for j in (range(n)) ]).reshape(len(a),n)
    Rev_Arr = np.flip(Arr,axis=1)
    print('First Arrangement of the Matrix')
    print(Arr)
    print('---------------------------------------------------------------------------------')
    print('Second Arrangement of the Matrix - In reverse order')
    print(Rev_Arr)

In [45]:
input_arr = np.array([3,4,5,6])
powers = 5
Alex_Theo_Vander(input_arr,powers)

First Arrangement of the Matrix
[[   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]
---------------------------------------------------------------------------------
Second Arrangement of the Matrix - In reverse order
[[  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]


# Question - 2 Given a sequence of n values x1, x2, ..., xn and a window size k>0,calculate the k-th moving average of the given sequence 

In [90]:
def moving_avg(sequence,window_len):
    arr = np.array(sequence)
    n = window_len
    a =[]
    for i in range(len(arr) - n + 1):
        b=[]
        for j in range(n):
            b.append(arr[i+j])
            if len(b) == n :
                a.append(sum(b)/len(b))
    return np.array(a)
        
        

In [91]:
sequence = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_len = 3
moving_avg(sequence,window_len)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])